### ISSUE TITLE
Feature request: Anchors aliases override

### ISSUE THREAD

**Issue by b4D8** [vubiostat/r-yaml#104]
Hi!

Thanks for your work on this package!

I figured anchors can be aliased but not override.

## Reproducible example

```r
"---
a: &anchor
  FOO: not working
b:
  <<: *anchor
  FOO: working" -> test

yaml::yaml.load(test)
```

## Result

```r
$a
$a$FOO
[1] "not working"

$b
$b$FOO
[1] "not working"
```

## Expected 

```r
$a
$a$FOO
[1] "not working"

$b
$b$FOO
[1] "working"
```

This feature doesn't seem to be in the specification but is implemented in some parsers (like  [json2yaml converter](https://www.json2yaml.com/convert-yaml-to-json)), and documented over the web ([here](https://dev.to/educative/advanced-yaml-syntax-cheatsheet-59ij) for instance).

Maybe an idea for further development (which would be really helpful in my current task...)

I you want, I'll reference this to libyaml which is probably responsible for this.

Cheers!

**Comment by spgarbet** [comment]
Reference: https://yaml.org/type/merge.html

**Comment by spgarbet** [comment]
I'm struggling to get the full YAML1.2 specification working. I don't see implementation of a feature outside that scope as possible for quite some time.
