### ISSUE TITLE
does not support large int

### ISSUE THREAD

**Issue by bakerwm** [vubiostat/r-yaml#112]
I have a `.yaml` file generated by python. In the following example, R could not deal with the large int. (default R support 32 bit, 2147483648). 
package `bit64::as.integer64(3209286105)` could support larger int.

```R
> readLines("aaa.yaml")
[1] "a: 3209286105"
> yaml::read_yaml("aaa.yaml")
$a
[1] NA

Warning message:
In yaml.load(string, error.label = error.label, ...) :
  NAs introduced by coercion: 3209286105 is out of integer range
```

**Comment by spgarbet** [comment]
r-yaml supports base R and has as little external dependencies as possible. 

It does support injection as `handlers`. For example:

```
> yaml::yaml.load("3209286105", handlers = list(int = function(x) bit64::as.integer64(x)))
integer64
[1] 3209286105
```
