### ISSUE TITLE
`n` is translated to `FALSE`

### ISSUE THREAD

**Issue by dipterix** [vubiostat/r-yaml#116]
When I try to read yaml file that passively obtained from other place. 

There is unquoted `n` in its name like this

```yaml
n: 100
```

The result of `yaml` translates `n` to `FALSE`

```r
$`FALSE`
[1] 100
```

I'm not very familiar with yaml format... Not sure if this is intended?

**Comment by spgarbet** [comment]
The dependent library is a C library and it supports YAML1.1. This is defined behavior in 1.1

See Issues #24 , #80, #103, and most importantly #76.
