### ISSUE TITLE
encode NA as null?

### ISSUE THREAD

**Issue by vankesteren** [vubiostat/r-yaml#118]
Hey all, 

excellent work on this package. Just a quick question: I thought the way this package encodes NA values is pretty strange, shouldn't `NA` in R become `null` in yaml?

```
R> library(yaml)
R> cat(as.yaml(list(a = 1, b = "hello", c = NA)))

a: 1.0
b: hello
c: .na
```

I'd like to see at least an option for this!

**Comment by vankesteren** [comment]
Update, I now realize that this can be achieved by the following handler:

```r
null_handler <- function(x) {
  if (!is.na(x)) return(x)
  res <- "null"
  class(res) <- "verbatim"
  return(res)
}
```

but this needs to be implemented for all NA types then! (`NA` has class `logical` but `NA_character_` has class `character`)

**Comment by spgarbet** [comment]
NULL and NA have different semantic meanings. There's a subtle but important distinction between the two, and it changes based on context. NA preservation is necessary and has to be distinct from NULL for R.
