### ISSUE TITLE
GH request: start making GH releases so as to enable `@*release` syntax from `remotes`

### ISSUE THREAD

**Issue by pawelru** [vubiostat/r-yaml#129]
As a package developer
I would like to specify `vubiostat/r-yaml@*release` syntax to automatically pull the latest release (done via `remotes` -> see https://remotes.r-lib.org/articles/dependencies.html?#github for docs)
Right now it fails with the following `No releases found for repo vubiostat/r-yaml.`.

**Comment by spgarbet** [comment]
I created a release here. Does that help?

**Comment by pawelru** [comment]
Worked well! Thank you!
