### ISSUE TITLE
Non-API Calls

### ISSUE THREAD

**Issue by shikokuchuo** [vubiostat/r-yaml#144]
R CMD check NOTEs are showing up for the package for R-devel:

https://cran.r-project.org/web/checks/check_results_yaml.html

> File ‘yaml/libs/yaml.so’:
    Found non-API calls to R: ‘SET_BODY’, ‘SET_CLOENV’, ‘SET_FORMALS’
  >
  > Compiled code should not call non-API entry points in R.
  >
 >  See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
  See section ‘Moving into C API compliance’ in the ‘Writing R
  Extensions’ manual for issues with use of non-API entry points.

There is a whole new set of closure-related functions in R4.5.0, and the Writing R Extensions recommendation is to backport these for older R versions: https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Creating-closures

Will provide a PR as I recently fixed this in {nanonext} e.g. at https://github.com/shikokuchuo/nanonext/blob/main/src/aio.c#L25-L33

**Comment by spgarbet** [comment]
On it's way to CRAN.
