### ISSUE TITLE
Support a validator function for yaml

### ISSUE THREAD

**Issue by renkun-ken** [vubiostat/r-yaml#19]
The `jsonlite` package has a function `validate()` to validate a json text. Is it possible to implement such a function for yaml text? Is there existing library that does this?

Or just `try()` parsing a yaml and see if error occurs?

**Comment by viking** [comment]
I don't know of an existing R library that will validate a YAML file without parsing it first. This might be a good feature, I'll consider it.

**Comment by jonocarroll** [comment]
I don't know if this is of interest, but this seems to work on the yaml files I have, plus the two in inst/test/files/ here
```r
## borrowed from {validate}
.readlines_utf8 <- function(file, encoding="unknown"){
  lines <- readLines(con=file, encoding=encoding)
  enc2utf8(lines)
}

valid_yaml <- function(f) {
    s <- .readlines_utf8(f)
    blank <- grepl("^$", s)
    sep <- grepl("^---$", s)
    top_level <- grepl("^[^ ]", s) & grepl(":", s)
    setting <- grepl("^ ", s) & (grepl(": ", s) | grepl(":$", s))
    list_item <- grepl("^[ -]", s) & grepl("^-", trimws(s))
    expected <- blank | sep | top_level | setting | list_item

    valid <- all(expected)
    if (!valid) {
      warning("unexpected yaml encountered... possible culprits:")
      for (err in which(!expected)) {
        warning(paste0(s[err], collapse = "\n"), call. = FALSE)
      }
    }
    valid
}
```
My main issue was spotting a missing colon, and this helps with that
```r
txt <- "
top:
  this: that
  something missing
  another: okay
"
f <- tempfile()
writeLines(txt, f)
valid_yaml(f)
[1] FALSE
Warning messages:
1: In valid_yaml(f) : unexpected yaml encountered... possible culprits:
2:   something missing 
```
If anyone's come up with anything better, I'm interested in that, too.

**Comment by spgarbet** [comment]
GIven that Jeremy has moved on, and the push is for yaml 1.2 support I don't see this as a feature that's going to get added.
