### ISSUE TITLE
Consider supporting an 'include' directive

### ISSUE THREAD

**Issue by eddelbuettel** [vubiostat/r-yaml#46]
In a number of use cases, YAML files are carried over from other, similar files.  An example may be YAML frontmatter for Rmarkdown files: certain formatting aspects (say, particular to an author or institution) are copied around from project to project.  

In other languages, _common_ elements can re-use by means of an `#include somefile` statement.  
And at least one other YAML parser implements this in the context of a [larger system for home automation](https://home-assistant.io/docs/configuration/splitting_configuration).    

This carried over from [here](https://github.com/eddelbuettel/linl/issues/2) and subsequent email discussion.  Having an include directive is yaml is probably easier than attempting to change pandoc or rmarkdown, and the issue really is local to the yaml frontmatter.

/cc @aaronwolen

**Comment by viking** [comment]
The easiest way to accomplish this right now is through the use of a `!include` tag and a custom handler:

```r
yaml.load_file("test.yml", handlers = list(include = function(fn) yaml.load_file(fn)))
```

That would only work for 1 level deep, but you could create a wrapper function to do infinite recursion:

```r
foo <- function(...) yaml.load_file(..., handlers = list(include = foo))
foo("test.yml")
```

**Comment by eddelbuettel** [comment]
Nice. One level may actually be good enough for us.

**Comment by spgarbet** [comment]
Can be done via handlers.

**Comment by eddelbuettel** [comment]
> Can be done via handlers.

It's been years since I would have needed this but I am still curious so _how?_  Can you post a short example, here or in the package?
