### ISSUE TITLE
Require option for evaluating !expr

### ISSUE THREAD

**Issue by viking** [vubiostat/r-yaml#47]

**Comment by kevinykuo** [comment]
@viking is there a way to get around the following warning for now

```
> yaml::yaml.load('!expr paste("orange")')
[1] "orange"
Warning message:
In yaml::yaml.load("!expr paste(\"orange\")") :
  R expressions in yaml.load will not be auto-evaluated by default in the near future
```

We're seeing this warning in a couple downstream packages e.g. https://github.com/rstudio/config/issues/12

**Comment by viking** [comment]
Currently not, I'm afraid, apart from the normal R mechanisms for turning off warnings (see the help for the suppressWarnings function). In the next release I plan on disabling expression evaluation by default and adding an option to turn it back on for safety/security reasons.

**Comment by viking** [comment]
Actually, you can avoid the warning by evaluating the text in a supplied handler like this:

```r
yaml.load("!expr paste('foo')", handlers = list(expr = function(x) eval(parse(text = x))))
```

**Comment by kevinykuo** [comment]
Thanks!!

**Comment by viking** [comment]
In the latest version of the yaml package (2.1.19) there is a parameter called `eval.expr` that you can explicitly set to TRUE if you want to avoid the warning. Alternately you can set the `yaml.eval.expr` global option like this:
```r
options("yaml.eval.expr" = TRUE)
```
See the help on the `yaml.load` function for more information.

**Comment by kevinykuo** [comment]
Thanks @viking !

**Comment by spgarbet** [comment]
@hadley This is the one you mentioned to me. The proposal is to have this off by default (it's on by default right now).

**Comment by hadley** [comment]
Right; in a new package I don’t think it should even be an option.
