### ISSUE TITLE
Serialisation error on Windows?

### ISSUE THREAD

**Issue by lionel-** [vubiostat/r-yaml#74]
The CRAN checks for vdiffr are currently failing on the Windows platforms: https://cran.rstudio.com/web/checks/check_results_vdiffr.html

```
> widget_slide(p1, p2)
    Warning in yaml.load(readLines(con), error.label = error.label, ...) :
     NAs introduced by coercion: 1.0 is not a real

    Error in if (length(x) != 1 || x == "" || grepl("[/\\]", x)) stop("Invalid argument '", :
     missing value where TRUE/FALSE needed
    Calls: <Anonymous> ... FUN -> do.call -> <Anonymous> -> validateScalarName
    Execution halted 
```

The error is triggered here: https://github.com/rstudio/htmltools/blob/4b34e98fc0de2d6f0a1c9ec2b87acce98edbf7a8/R/html_dependency.R#L111

Likely because it was passed `version` was parsed as `NA`. This warning after calling `yaml.load()` seems very relevant:

```
NAs introduced by coercion: 1.0 is not a real
```

And indeed here is the corresponding yaml file:

```yaml
dependencies:
  - name: twoface
    version: 1.0
    src: htmlwidgets/lib
    script: twoface.js
```

Perhaps you have some idea why this would fail on some Windows platforms? I couldn't reproduce in Virtualbox.

**Comment by lionel-** [comment]
That's probably because strtod is dependent on the locale. https://en.cppreference.com/w/cpp/string/byte/strtof Some locales use commas as decimal separator.

I couldn't find a locale to reproduce the failure though. Not sure if it'd make sense to set the locale to C before parsing or if that should be handled by the user. In the latter case, perhaps it should become a parameter to `yaml.load()` that defaults to the current locale?

**Comment by spgarbet** [comment]
If you don't have the locale installed, it treats it as the "C" locale. This will install a locale with a "," behavior on a Linux box.

```
sudo locale-gen de_DE.UTF-8
```

Then one can compile this example and it works. Actually compile and run this before installing the locale. It doesn't work. Then install the locale and it works.

```
#include <stdio.h>      /* printf, NULL */
#include <stdlib.h>     /* strtod */
#include <locale.h>

int main ()
{
  char szOrbits[] = "365,24 29,53";
  char* pEnd;
  double d1, d2;

  setlocale(LC_NUMERIC, "de_DE.UTF-8");
  d1 = strtod (szOrbits, &pEnd);
  d2 = strtod (pEnd, NULL);
  printf ("The moon completes %.2f orbits per Earth year.\n", d1/d2);
  return 0;
}
```

**Comment by spgarbet** [comment]
Cannot reproduce.
