### ISSUE TITLE
Handlers of type `builtin` should not be rejected

### ISSUE THREAD

**Issue by jchrom** [vubiostat/r-yaml#99]
Hello! 

Using the current CRAN version, I wanted to use `as.double` for integer handler, and got this strange behavior:

```
yml = readLines("dev/yaml/github.yaml", warn = FALSE) #GitHub's OA spec

r = yaml::yaml.load(yml, handlers = list(int = as.double))
Warning messages:
#> 1: In yaml::yaml.load(yml, handlers = list(int = as.double)) :
#>  Your handler for type 'int' is not a function; using default
```

But this works no problem:

```
r = yaml::yaml.load(yml, handlers = list(int = function(x) as.double(x)))
```

Handlers of type `builtin` should be accepted I think, though the workaround is quite painless.

**Comment by viking** [comment]
Looks like `as.double` is a different type of function than what I'm checking for:

```c
      if (TYPEOF(s_handler) != CLOSXP) {
        warning("Your handler for type '%s' is not a function; using default", name);
        s_handler = R_NilValue;
      }
```

I should be able to fix it in the next release. Thanks for your bug report.

**Comment by spgarbet** [comment]
as.double is a BUILTINSXP
